auth:
  whitelist:
    - /api/auth/login/**
    - /api/auth/refresh/**
    - /api/auth/register/**
spring:
  jwt:
    secret: "V3o5L2hXnZsT8O0x5kYbGk1mQ2sR9eZpYvQfHjKlL7I="
    jwt-expiration-ms: 900000   # 15mins
    refresh-expiration-days: 7

  data:
    redis:
      host: localhost
      port: 6379